// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfqeqqxeybmnxqvaleyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmcWVxcXhleWJtbnhxdmFsZXlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNzg3OTgsImV4cCI6MjA2MjY1NDc5OH0.X8DvtYVuYW3T0Etsk40K5swe9WgQ6d-_UTzGhhVajew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);